micronaut:
  application:
    name: vk-unlocker
  server:
    cors:
      enabled: true
      localhost-pass-through: true
  router:
    static-resources:
      miniapp:
        enabled: true
        mapping: /miniapp/**
        paths: classpath:miniapp
jackson:
  deserialization:
    READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
# Тут думаю всё понятно.
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/your_database_name
    driverClassName: org.mariadb.jdbc.Driver
    username: your_username
    password: your_password
vk-unlocker:
  # IP адрес или домен где это всё запущенно
  domain: https://localhost:8080
  # ID миниприложения для сохранения видосов
  miniAppId: 52483593
  group:
    # ID группы
    id: group_id
    # Token группы
    token: group_token
  # Пользователь для скачивания видео и вступления в группы
  download-user:
    token: download_user_token
  # Пользователь для загрузки видео в группу
  upload-user:
    token: upload_user_token
  # Пользователь для "тыканья" видосов на наличие блокировки, единственный READ ONLY
  poke-user:
    token: poke_user_token
  private-groups: false