// Autogenerated from vk-api-schema. Please don't edit it manually.
package ru.spliterash.vkVideoUnlocker.vkApiFix;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.video.LiveSettings;
import com.vk.api.sdk.objects.video.Video;
import com.vk.api.sdk.objects.video.VideoFiles;
import com.vk.api.sdk.objects.video.VideoFull;

import java.util.Objects;

/**
 * VideoFull object
 */
public class VideoFullFix extends Video implements Validable {
    @SerializedName("files")
    private VideoFilesFix files;

    /**
     * Settings for live stream
     */
    @SerializedName("live_settings")
    private LiveSettings liveSettings;

    public VideoFilesFix getFiles() {
        return files;
    }

    public VideoFullFix setFiles(VideoFilesFix files) {
        this.files = files;
        return this;
    }

    public LiveSettings getLiveSettings() {
        return liveSettings;
    }

    public VideoFullFix setLiveSettings(LiveSettings liveSettings) {
        this.liveSettings = liveSettings;
        return this;
    }
}
